version: 2
updates:
  - package-ecosystem: "pip" 
    directory: "/"
    schedule:
        interval: "weekly"
    labels:
        - "dependencies"
        - "automerge"
        - "auto-approve"
    open-pull-requests-limit: 5
    ignore:
        - dependency-name: "cdktf"
          update-types: ["version-update:semver-major"]
        - dependency-name: "cdktf-cdktf-provider-*"
          update-types: ["version-update:semver-major"]
        - dependency-name: "pytest"
          update-types: ["version-update:semver-major"]
        - dependency-name: "snapshottest"
          update-types: ["version-update:semver-major"]
    groups:
        cdktf:
            patterns:
                - "cdktf"
                - "cdktf-cdktf-provider-*"
        test:
            patterns:
                - "pytest" 
                - "snapshottest"
