version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "automerge"
      - "auto-approve"
    # only update hashicorp actions, external actions managed by tsccr
    allow:
      - dependency-name: "hashicorp/*"
  - package-ecosystem: "pip" 
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "automerge"
      - "auto-approve"
    open-pull-requests-limit: 5
    versioning-strategy: "increase-if-necessary"
    allow:
      - dependency-type: "all"
    ignore:
      # For providers, ignore all patch updates for version updates only
      - dependency-name: "cdktf-cdktf-provider-*"
        update-types: ["version-update:semver-patch"]
    groups:
      cdktf:
        patterns:
          - "cdktf"
          - "cdktf-cdktf-provider-*"
      test:
        patterns:
          - "pytest" 
          - "snapshottest"
# We are purposely not (yet) using Dependabot to update dependencies for the frontend, because there are no frontend tests we can use to verify it didn't break
