version: 2
updates:
  - package-ecosystem: "pip" 
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "automerge"
      - "auto-approve"
    open-pull-requests-limit: 5
    ignore:
      # For providers, ignore all patch updates for version updates only
      - dependency-name: "cdktf-cdktf-provider-google-beta"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "cdktf-cdktf-provider-local"
        update-types: ["version-update:semver-patch"]
    groups:
      cdktf:
        patterns:
          - "cdktf"
          - "cdktf-cdktf-provider-*"
      test:
        patterns:
          - "pytest" 
          - "snapshottest"
# We are purposely not (yet) using Dependabot to update dependencies for the frontend, because there are no frontend tests we can use to verify it didn't break
