name: automerge
on:
    pull_request_target:
        types:
        - opened
        - labeled
        - ready_for_review
        - reopened
        - synchronize
    check_suite:
        types:
            - completed
    status: {}
    schedule:
        - cron: 7 13 * * *
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
    automerge:
        runs-on: ubuntu-latest
        permissions: {}
        steps:
        -   name: automerge
            uses: pascalgn/automerge-action@22948e0bc22f0aa673800da838595a3e7347e584
            env:
                GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                MERGE_RETRIES: "20"
                MERGE_RETRY_SLEEP: "60000"
                MERGE_METHOD: squash
                UPDATE_METHOD: rebase
