name: Synth
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
      - reopened
  workflow_dispatch: {}

jobs:
  synth:
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/hashicorp/jsii-terraform
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - name: ensure correct user
        run: chown -R root /__w/cdktf-integration-serverless-python-gcp-example/
      - name: Create Yarn Project
        run: yarn init --yes
      - name: Add CDKTF CLI
        run: yarn global add cdktf-cli
      - name: Install Python Dependencies
        run: pipenv install --dev
      - name: Synth
        run: cdktf synth
