name: Test Against Regression
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
      - reopened
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/hashicorp/jsii-terraform
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - name: Find Python Version
        id: python-version
        run: echo "python_version=$(cat Pipfile | grep 'python_version =' | awk -F'"' '{gsub("=","",$2); print $2}')" >> "$GITHUB_OUTPUT"
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ steps.python-version.outputs.python_version}}
      - name: ensure correct user
        run: chown -R root /__w/cdktf-integration-serverless-python-gcp-example/
      - name: Generate Pipfile.lock
        run: pipenv lock
      - name: Install Python Dependencies
        run: pipenv requirements | sed -nE 's/^([[:alnum:]-]+==[0-9]+\.[0-9]+\.[0-9]+).*$/\1/p' | PIPENV_VENV_IN_PROJECT=1 bash -c 'dependencies=$(cat); echo "$dependencies" | while read -r requirement; do echo "INSTALLING $requirement"; pipenv run pip install "$requirement"; done'
      - name: Pytest
        run: PROJECT_ID=myproject pipenv run pytest
